### PR TITLE
New Project - students list

### LINKED ISSUE #9: create index html for students list
put the HTML in the root folder

### PR DESCRIPTION
**Pull request by eden-amar**

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
@eden-amar this file should have the basic HTML structure (head, body..).

**Comment by eden-amar** [comment]
Ok
I did “touch” to the file so I didn’t open the VS.
I’m on it.

בתאריך יום ב׳, 23 בינו׳ 2023 ב-22:06 מאת David Meir-Levy <
***@***.***>:

**Comment by eden-amar** [comment]
> @eden-amar this file should have the basic HTML structure (head, body..).
> @davidmeirlevy  I fixed it

**Review by davidmeirlevy — APPROVED** [review]

**Comment by davidmeirlevy** [comment]
Make sure you choose "squash and merge" for this PR. ✌️

**Pull request merged**
